### ISSUE TITLE
Create vagrant script to automate making the box

### ISSUE THREAD

**Issue by bjartwolf** [bjartwolf/Kebab#1]

**Comment by bjartwolf** [comment]
Noe sure how easy it it to install monodevelop extesions etc with scripts https://github.com/bjartwolf/Kebab/blob/master/ubuntu-setup.md

**Comment by Glorp** [comment]
Turns out there's a command line tool at least.
https://github.com/bjartwolf/Kebab/commit/956bbc527f0a7034ffcb7ee599d36bf2e4507a4d

**Comment by bjartwolf** [comment]
Probably not going to supply virtual boxes as VS Code is getting crossplatform'ish
